### ISSUE TITLE
Python package / build (3.5) (push) — build (3.5) Error

### ISSUE THREAD

**Issue by JaimePSantos** [den01-python-programming-exercises/exercise-2-4-comparing-numbers-JaimePSantos#1]
Hello,
pytest works fine with my solution, however that build gives me this error 
/src/exercise.py:6:53: E999 SyntaxError: invalid syntax
        print(f"{number1} is greater than {number2}.")

**Comment by Scott3142** [comment]
Python introduced f-strings in 3.6, so the 3.5 build test will fail if you use them. 

You can modify the workflow.yml file (in .github/workflows/) to remove the test against 3.5 or edit the code so that it doesn't use f-strings. 

Hopefully that's helpful. At some point I might remove the 3.5 test requirement so that f-strings can be used with the tests.

**Comment by JaimePSantos** [comment]
Thanks for the quick reply and all the effort to port this tutorial to python, it was exactly what i was looking for. Great work!
